### ISSUE TITLE
Private Match

### ISSUE THREAD

**Issue by atmoner** [Lierrmm/WWIIStatsViewer#2]
Hello, nice job!
I am looking to retrieve statistics for private match but impossible to find! 
However, I see a variable "privateMatch" on this endpoint:
`api/papi-client/crm/cod/v2/title/wwii/platform/{platform}/gamer/{gamertag}/matches/days/5/`

![mozilla firefox_032](https://user-images.githubusercontent.com/1071490/34443814-ef0eabde-ecc9-11e7-886c-9c4475a85508.jpg)

An idea?

**Comment by ImNotLiam** [comment]
I'm not sure if there is a way to grab the stats for private match.  I guess the way you could do it is just by recent matches if privateMatch was true. 

I'll have a look through the API and see if I can find anything.
