### ISSUE TITLE
[QUESTION]: A way around CORS

### ISSUE THREAD

**Issue by Antimated** [Lierrmm/WWIIStatsViewer#3]
Hey nice code you got there. I was wondering if there is a way to pull the stats of the api with jQuery? Tried pulling the stats but I keep getting CORS errors. So I tried the usual stuff (adding an asterix as allow origin header) but this still doesn't work. Actually I don't get any callback at all when I try this... Any idea's on how this problem could be fixed? Trying to make a personal web app to get my KDR and making a calculator to show how many games I have to play to get to my desired KDR.

			$.get({
				method: "GET",
				type: 'json',
				url: "https://my.callofduty.com/api/papi-client/crm/cod/v2/title/" + game + "/platform/" + platform + "/gamer/" + gamertag + "/profile/",
				headers: {
					'Content-Type':'application/json;charset=UTF-8',
					'Access-Control-Allow-Origin:': '*',
					'Access-Control-Allow-Methods:':'GET',
					'Access-Control-Allow-Headers:':'Content-Type, Content-Range, Content-Disposition, Content-Description',
					'Access-Control-Max-Age:':'300'
				},
				success: function(data) {
					console.log(data);
					//no data here :(
				}
			});

EDIT: I don't want to use anything like npm or stuff like that. In the future I would like to upgrade to pure ES6

**Comment by ImNotLiam** [comment]
Are you doing the requests on a secure page? If not, this will be why you are getting CORS errors.

Try it on a site with https. ( create your own certificate if need be ) and it should work.

**Comment by Antimated** [comment]
Didn’t enable ssl yet.  Want to run it on a local MAMP server. Is SSL possible on MAMP or do I have to get myself a live environement with an ssl certificate?

**Comment by ImNotLiam** [comment]
https://gist.github.com/jfloff/5138826 - this should be able to help you :)

**Comment by Antimated** [comment]
That's a solution for mac but not for windows :(. Installed WAMP now on Windows instead and I got my ssl connection to work (sorta). Problem is I still get the CORS error:

**Firefox**
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://my.callofduty.com/api/papi-client/crm/cod/v2/title/wwii/platform/psn/gamer/{mygamertaghere}/profile/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Chrome**
`Failed to load https://my.callofduty.com/api/papi-client/crm/cod/v2/title/wwii/platform/psn/gamer/{mygamertaghere}/profile/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localhost' is therefore not allowed access. The response had HTTP status code 403.`

Whenever I add 'Access-Control-Allow-Methods:':'GET' I seem to get no error, but also no data is returned.

**Comment by ImNotLiam** [comment]
Hmm weird. I think I tried it with ASP and it worked locally but not on a server. 

This is why I stuck to Node and the request module.
If you look at @tustin25's github. Their is an API for the Cod API you could potentially reference.

**Comment by Antimated** [comment]
It's in Csharp though :( I'll have to find a way around this issue :/ Also tried with ES6 and it's the same issue.
